[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool.black]
line-length = 79

[tool.poetry]
authors = ["Sam Roeca <samuel.roeca@gmail.com>"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Console",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Utilities",
  "Typing :: Typed",
]
description = "Toml sorting library"
homepage = "https://github.com/pappasam/toml-sort"
include = ["README.md"]
keywords = ["toml", "sort", "cli", "unix", "utility"]
license = "MIT"
name = "toml-sort"
readme = "README.md"
repository = "https://github.com/pappasam/toml-sort"
version = "0.3.0"

[tool.poetry.dependencies]
click = "^7.0"
python = "^3.6"
tomlkit = ">=0.5.5"

[tool.poetry.dev-dependencies]
black = {version = "^19.3b0", allows-prereleases = true}
mypy = "^0.720.0"
pre-commit = "^1.18"
pylint = "^2.3"
pytest = "^5.0"
tox = "^3.13"

[tool.poetry.scripts]
toml-sort = 'toml_sort.cli:cli'

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36,py37
isolated_build = true
skipsdist = true
[testenv]
platform = linux
whitelist_externals = poetry
skip_install = true
commands =
  poetry install
  poetry run mypy toml_sort
  poetry run pylint toml_sort tests/
  poetry run pytest
"""
